name: Automate iOS Build and TestFlight upload

 

on:

  push:

    branches:

      - main

 

jobs:

  build_and_upload:

    name: Build and Upload

    runs-on: macos-latest

    

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

 

      - name: Install Xcode

        run: sudo xcode-select --switch /Applications/Xcode.app

 

      - name: Install CocoaPods

        run: |

          gem install cocoapods

          pod install

          

      - name: Clean Project

        run: xcodebuild clean -workspace AutomationSample.xcworkspace -scheme AutomationSample

 

#      - name: Build IPAA

#        run: xcodebuild archive -workspace SampleCICD.xcworkspace -scheme SampleCICD -archivePath SampleCICD.xcarchive -allowProvisioningUpdates

 

      - name: Build IPAA

        run: xcodebuild -workspace AutomationSample.xcworkspace -scheme AutomationSample -configuration Release clean archive -archivePath AutomationSample.xcarchive CODE_SIGNING_ALLOWED=NO -allowProvisioningUpdates

 

#      - name: Export IPA

#        run: xcodebuild -exportArchive -archivePath SampleCICD.xcarchive -exportPath . -exportOptionsPlist ExportOptions.plist

        

      - name: Export IPA

        run: xcodebuild -exportArchive -archivePath AutomationSample.xcarchive -exportPath . -exportOptionsPlist AutomationSample/ExportOptions.plist

 

      - name: List Files

        run: ls -lh

 

      - name: Install Transporter

        run: brew install --cask transporter

 

      - name: Upload to TestFlight

        run: transporter upload -package AutomationSample.ipa -username ${{ secrets.APPLE_ID_USERNAME }} -password ${{ secrets.APP_SPECIFIC_PASSWORD }} -itc_provider ${{ secrets.ITC_TEAM_ID }}

